### ISSUE TITLE
Mark library as CLS compliant

### ISSUE THREAD

**Issue by nzbart** [nlkl/Optional#10]
Microsoft advises that library implementers should mark their APIs as CLS compliant using [CLSCompliantAttribute](https://msdn.microsoft.com/en-us/library/system.clscompliantattribute(v=vs.110).aspx): 
* [CA1014: Mark assemblies with CLSCompliantAttribute](https://msdn.microsoft.com/en-us/library/ms182156.aspx)

Since we mark our libraries as CLS compliant in accordance with this, and since your library is by default not CLS compliant, we would need to scatter `[CLSCompliant(false)]` statements throughout our APIs if we used your library.

Unfortunately, this is a show-stopper for us.

One good way to make sure that issues like this don't affect down-stream users of your library is to take advantage of [Visual Studio's Code Analysis](https://msdn.microsoft.com/en-us/library/3z0aeatx.aspx) feature, which warns library developers about common issues like this.

**Comment by nzbart** [comment]
I've added a pull-request since this was actually quite a simple job.

**Comment by nlkl** [comment]
Thank you for the info and the pull request!

To be completely honest, I hadn't given it any thoughts - I will merge the pull request and hopefully have a new release on Nuget this weekend.

**Comment by nlkl** [comment]
I have merged the pull request and am closing this for now.
