### ISSUE TITLE
Advice required: how to deal with APIs that don't use Option?

### ISSUE THREAD

**Issue by nzbart** [nlkl/Optional#13]
I want to use `Option` in my code, but sometimes I need to get a `null` value when passing to another API. I'd like to be able to treat `Nullable<T>` value types in a similar way to class types. What are your thoughts on the idea in the code below? 

``` cs
    public static class OptionalExtensions
    {
        public static T? GetUnsafeValueOrStructNull<T>(this Option<T> option)
            where T : struct
        {
            return option.HasValue
                ? option.ValueOrFailure()
                : (T?)null;
        }

        public static T GetUnsafeValueOrClassNull<T>(this Option<T> option)
            where T : class
        {
            return option.ValueOr(default(T));
        }
    }
```

Ideally, I'd just use your library rather than create non-standard extensions for something so fundamental, so if you could point me in the right direction, I'd like to avoid using these extension methods.

**Comment by nlkl** [comment]
Actually, I don't think it is a bad thing as such, to have a set of custom extension methods in your project. Optional covers most common usage scenarios, but will never be able to cover them all.

The use case you mention is actually fairly common, but I have deliberately kept it slightly difficult to convert an optional back to a null value, as converting back to null would defeat much of the purpose of using option types in the first place. I suspect that a dedicated `ValueOrNull()` method would encourage some bad practices, that I would rather see avoided.

I will think about whether to include such a method under the Optional.Unsafe namespace, but for now I would suggest going ahead and adding your own extension method, or simply using Match and ValueOr directly:

```
option.Match(v => v, () => default(int?)); // value type
option.ValueOr(default(string)); // reference type
```

**Comment by kodfodrasz** [comment]
👍 for @nlkl 's advice on best practice. Your code stays cleaner easier to reason about that way.

**Comment by atifaziz** [comment]
> I have deliberately kept it slightly difficult to convert an optional back to a null value, as converting back to null would defeat much of the purpose of using option types in the first place. 

I don't think anyone is trying to defeat the purpose. One wouldn't be using your wonderful Optional if they weren't aware of the good and the bad in the first place. 😄 Adding a method along the lines of `ValueOrNull()` under `Optional.Unsafe` is a good compromise and a clear warning.

**Comment by nlkl** [comment]
Closing this, as a dedicated issue for the improvement has been added (#29)
