### ISSUE TITLE
PCL support

### ISSUE THREAD

**Issue by 2moveit** [nlkl/Optional#15]
Hi,
I know .NET Standard is the way to go...in the future... but is it possible to support PCLs, too? 
BR

**Comment by nlkl** [comment]
Hi - and thank you for your interest in Optional!

I will take a closer look, to see how much it takes to target a reasonable subset of the PCL profiles.

As a very rough starting point, I can see that Newtonsoft.Json includes the following profiles:

**Profile259**
* .NETFramework 4.5
* .Windows 8.0
* .WindowsPhone 8.1
* .WindowsPhone 8.0

**Profile328**
* .NETFramework 4.0
* Silverlight 5.0
* Windows 8.0
* WindowsPhone 8.1
* WindowsPhone 8.0

Do you think that would be "sufficient" ?

**Comment by 2moveit** [comment]
Cool. I'm using it with Xamarin. I think it is 279.

    .NETFramework 4.5
    .Windows 8.0
    .ASP.NET Core 1.0
    .WindowsPhone 8.1
    .Xamarin.Android
    .Xamarin.iOS
    .Xamarin.iOS (Classic)

**Comment by candoumbe** [comment]
Hi !

Any update on this ? 
I also would like to have it working with Xamarin (as @2moveit)


Keep up the great work !

**Comment by candoumbe** [comment]
Hi again !
I looked at your code yesterday in order to add support for `Xamarin.Android` and `Xamarin.iOS` and it turns out that there only one minor change to make in order for Optional to work on these platforms : targetting `netstandard1.4` framework.

Do you want me to PR something on this ?

**Comment by nlkl** [comment]
Hi @candoumbe - and thanks for your interest in Optional!

To be completely honest, PCL support has been one of those things I have been secretly avoiding/postponing, as it is more and more a legacy concept, and a rather convoluted one on top of that (lots of different PCL targets and so forth).

But as you mention, it seems Xamarin now have Netstandard 1.4 support, which is a much easier target. 

Luckily, Optional is already available for Netstandard 1.0, with which Netstandard 1.4 is compatible. As such, you should be able to simply go ahead and install the latest Optional Nuget package, and it should just work.

Hope it helps - feel free to tell if you encounter any problems.

 / Nils

**Comment by candoumbe** [comment]
Hi @nlkl !
Thanks for your answer but I keep running into the same issue (maybe I'm doing something wrong). This is the error I get when referencing your package : 
```
Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Optional, Version=4.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
Nom de fichier : 'Optional.dll'
   à Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   à Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   à Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   à Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	Esabora.Mobile.Droid			
```

As you said, because the Optional v4.0.0 nuget package target `netstandard1.0`, it should be compatible with Mono profile but it seems it's not.

For the package to work, I had to : 
- explicitly specify to also target `netstandard1.4`
- conditionally exclude the `SerializableAttribute` on both `Option<T>` and `Option<T, TException>` classes.

I can make a PR if you want to take a look at the potential changes needed to fix this (all tests are passing).

**Comment by nlkl** [comment]
Due to the latest development on the .NET Core and .NET roadmaps, PCL will not be prioritized.

/ Nils
