### ISSUE TITLE
Interopt with Async Entityframework functions

### ISSUE THREAD

**Issue by nojaf** [nlkl/Optional#25]
I'm having the following code:

```charp
var terms = await _context.Terms.FindAsync(id);
return terms != null ?
Option.Some<TermsModel, Exception>(new TermsModel(terms.Id.ToString(), terms.DocumentUrl)) :
Option.None<TermsModel, Exception>(new RecordNotFoundException($"No general terms were found for the configured id {id}"));
```

Is/was there a way to avoid the null check and use an extension method to get an option of the FindAsync result?

**Comment by nlkl** [comment]
Hi,

At the moment you can write:

```
return (await _context.Terms.FindAsync(id))
    .SomeNotNull(() => new RecordNotFoundException(...))
    .Map(terms => new TermsModel(...));
```

Currently there is no extension method corresponding to FindAsync, unfortunately. However, I will make a quick investigation, to see if it makes sense to include it in the Optional.Collections package or elsewhere.

For now, I suggest you add your own DbSet-specific extension methods, and then it can be easily swapped if I decide to include it in one of the official packages.

**Comment by nojaf** [comment]
Thanks for the quick response. Issue can be closed but maybe you want to wait after the investigation. Up to you.

**Comment by nlkl** [comment]
Closing this for now.
