### ISSUE TITLE
Q: filter a list of either monads

### ISSUE THREAD

**Issue by nojaf** [nlkl/Optional#28]
I have a list of `Option<A,B>` and I want to filter to have a list of `A` and a list of `B`

```csharp
List<Option<A,B>> source = GetList();

var a =
    source.Select(x => x.Match(a => a, b => null).Where(x => x != null);

var b =
    source.Select(x => x.Match(a => null, b => b).Where(x => x != null);
```

Is there a better way of doing this?

**Comment by nlkl** [comment]
Hi,

It depends. In general, the preferred way to do this would be:

```csharp
var a = source.SelectMany(x => x.ToEnumerable());
```

However, this only works for the `Some` case, and for symmetry reasons I would stick an approach that works for both cases, when both cases are needed.

If this is a recurring pattern in your code base, you could consider defining specific helper methods for such purposes, e.g.:

```csharp

// Allows you to write: source.SelectMany(option => option.WithoutValue().ToEnumerable());

public static Option<TException> WithoutValue<TValue, TException>(this Option<TValue, TException> option)
{
    return option.Match(_ => Option.None<TException>(), exception => exception.Some());
}

// Optionally, you could even write specific LINQ extensions:

public static IEnumerable<TValue> Values<TValue, TException>(this IEnumerable<Option<TValue, TException>> source)
{
    if (source == null) throw new ArgumentNullException(nameof(source));
    return source.SelectMany(option => option.ToEnumerable());
}

public static IEnumerable<TException> Exceptions<TValue, TException>(this IEnumerable<Option<TValue, TException>> source)
{
    if (source == null) throw new ArgumentNullException(nameof(source));
    return source.SelectMany(option => option.WithoutValue().ToEnumerable());
}
```

In general, I don't think you should be afraid to introduce a bit of custom functionality, to ease the integration with the rest of your code base - I typically do this all the time (and only the most general use cases are integrated back into Optional itself).

However, I do have some plans for the Either-version of Option, but am still considering how to make these as painless to consumers of the library as possible.

**Comment by nojaf** [comment]
Ah I see, thanks! This is a better way of doing this.
Great to hear you have plans for the `Either` monad. I've been playing around with railway oriented programming so I'm definitely all ears.
