### ISSUE TITLE
Add ValueOrDefault() to Optional.Unsafe namespace

### ISSUE THREAD

**Issue by nlkl** [nlkl/Optional#29]
Based on the discussion in #13, I think it would be fair idea to add a ValueOrDefault() method (returning the value or default(TValue)) to the Unsafe namespace.

The need for such a function arises rather often due to interop with the rest of .NET, and writing `option.ValueOr(default(TValue))` becomes rather cumbersome for complicated type signatures for TValue. Similarly, `option.ValueOr(null)` is unfortunately a bit of a trap of its own, as it will default to the Func-overload of the method, and throw an ArgumentNullException.

**Comment by nlkl** [comment]
Fixed in commit f063002

**Comment by nzbart** [comment]
@nlkl It's great to see that this feature has been added! Do you have any idea when you'll publish a new version to NuGet?

**Comment by nlkl** [comment]
Hi @nzbart - I don't have a specific date yet, but I hope to put 4.0.0 out as a pre-release Nuget package in the very near future.

- Nils
