### ISSUE TITLE
Integrate Trasvis CI into the project

### ISSUE THREAD

**Issue by kuskmen** [nlkl/Optional#39]
At some stage, it will be nice to have Travis CI into the project along with other DevOps tools. I am not a DevOps, but I can invest some time in helping you for that. I am junior developer and I like the idea of the project. Nothing will make me happier than contributing with whatever I can. 

If you are interested we can get in touch 👍

**Comment by nlkl** [comment]
This is lot currently a priority I’m afraid, but might reconsider at a later point.

/ Nils
