### ISSUE TITLE
Publish version 4 on NuGet

### ISSUE THREAD

**Issue by nzbart** [nlkl/Optional#48]
It appears that you've already prepared to release version 4 on NuGet: 61aadc6e7c45d61b11f980cf03c544f4da043980.

Are you confident enough to make version 4 the official version? It has some useful features that I need, and I currently have to manually select the pre-release version.

**Comment by nlkl** [comment]
Hi,

Yes, at this point it should be ready for a release, and I will publish an official version early to mid January. It will be almost unchanged from the RC version.

Hope that will be timely enough - until then, feel free to use the pre-release version (even if a bit more cumbersome).

Thanks for your patience!

Best regards,
/ Nils

**Comment by nlkl** [comment]
Version 4.0.0 is now live on nuget.

/ Nils
