### ISSUE TITLE
ToOption()

### ISSUE THREAD

**Issue by slimshader** [nlkl/Optional#49]
Hi, new to the library and first things that really strikes me that it is possible to create Some<T>(null). Shouldn't Option be a guard against nulls? Current design gives no guarantees that Some state / HasValue actually means that Option has value. Anyways, what do you think about ToOption() extension method that would actually check for null and return None in that case and Some otherwise?

**Comment by thorhj** [comment]
Hi,

I think you are looking for the extension method `.SomeNotNull()`. In regards to allowing null values in `Some` has been considered by @nlkl, see more here: https://github.com/nlkl/Optional/issues/14

**Comment by nlkl** [comment]
I will close this for now. Feel free to reopen, if you have any additional comments/questions  :)
