### ISSUE TITLE
Include short changelog in release notes

### ISSUE THREAD

**Issue by wldevries** [nlkl/Optional#51]
I have multiple projects using Optional and I'm unsure of when to update and what to expect when I do.

**Comment by nlkl** [comment]
Hi,

Actually, I do maintain a simple changelog here: https://github.com/nlkl/Optional/wiki/Changelog

You're right, though, that I should probably include the changelog under the specific releases, as it might be the more obvious place to look for it.

/ Nils

**Comment by wldevries** [comment]
Cool thanks!
