### ISSUE TITLE
Functor, Applicative and Monad Extensions?

### ISSUE THREAD

**Issue by leandromoh** [nlkl/Optional#55]
Hello, is there extensions for classic functional typeclasses (Fmap, Bind, etc)  for Option type or others? 

http://adit.io/posts/2013-04-17-functors,_applicatives,_and_monads_in_pictures.html

**Comment by nlkl** [comment]
Hi - and thank you for your interest in the project!

In fact, Option is an instance of functor, applicative and monad (amongst others), although the names are a bit different from the similar names in Haskell:

Functor:

Option has a `Map(...)` method, corresponding to e.g. `fmap` in Haskell:

```
var option2 = option1.Map(x => x + 1);
```

Applicative:

```
// "pure"
var option = Option.None<int>();
```

// "

```
Option<Func<S, T>>, Option<S>
return option.FlatMap(pt2.Map)
```

**Comment by nlkl** [comment]
Hi - and thank you for your interest in the project!

In fact `Option` is Monad and a Functor (amongst others), implemented via the methods `.Map(...)` (corresponding to `fmap` in Haskell) and `.FlatMap(...)` (corresponding to `>>=`/bind) and `Option.None<T>()` (corresponding to `pure`/`return`).

Optional doesn't actually provide the actual Applicative instance functions out-of-the-box, as they are simply not that useful in C# context. They are however easily defined using `Map` and `FlatMap` if you need them.

Best regards,
/ Nils

**Comment by leandromoh** [comment]
I see. Thanks for reply. I am using `Optional` in one of my projects, and sometimes found useful to add the below method to wrap third-party code. what do you think about to add it to the library?

```c#
        public static Option<T> TryFunc<T>(this Func<T> function)
        {
            try
            {
                return function().Some();
            }
            catch (Exception ex)
            {
                return Option.None<T>();
            }
        }
```

example of use:

```c#
        public Option<Person> GetById(long Id) => TryFunc(() =>
        {
            return PersonRepository.GetById(Id);
        });
```

**Comment by nlkl** [comment]
Actually, I have been playing out with this idea under Optional.Utilities (the only major difference being, that I pass along the exception in an `Option<T, Exception>`, such as not to simply swallow it), but as the Optional.Utilities package is probably not going to see any releases in the near future, I am still to figure out exactly what to do with it.

**Comment by nlkl** [comment]
Closing for now (but will reconsider the situation as part of my next revisit of Optional.Utilities)
