### ISSUE TITLE
Match always needs both options

### ISSUE THREAD

**Issue by nojaf** [nlkl/Optional#6]
In some scenarios you don't care if the Option<T> is None.

```csharp
           myVal.Match(t =>
            {
                Log(t);
            }, () => { });
```

Would it not make sense to add an overload that doesn't require an none delegate?

**Comment by nlkl** [comment]
You are completely correct, and I actually considered that for a long time. 

However, I don't really like how it breaks symmetry, with the value-returning `Match`. I considered naming it `If(...)` instead, but in the end I ended up with the following solution:

```csharp
foreach (var value in option)
{
    Console.WriteLine(value);
}
```

This is currently the preferred way to handle only the Some-case.

**Comment by nojaf** [comment]
Feels kinda weird using a foreach for a single value. Or am I missing something here?

**Comment by nlkl** [comment]
Yes, and no - until you realize that an option can actually be considered a container, that can hold either 0 or 1 elements.

In general, I have kept the interface a bit different from collections, though, but I felt it adequate to use this approach here, as it reads quite well (for each value in this container...)
