### ISSUE TITLE
Mark Map and FlatMap as Obsolete and rename to F# variants (not Scala)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [nlkl/Optional#65]
I guess **Bind** and **Return** are better for .NET functions ecosystem rather than  **FlatMap** and **Map**, I if am not mistaken. So people could easily jump from C# and F# still having same vocabulary. I guess it is more fruitful than allow Scala programmers to jump into C#. I guess Haskell also have **bind** .  Other alternative retain only **SelectMany** and **Select**, but document in method documentation that these are  **Bind** and **Return** like in F#. 

https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/computation-expressions

As of now this project has no so best option from available regarding these names.  Documentation still could retain what is what. Including some metaphors like `aggregatable`, `composable` (Scot Wlaschin like). But API would have one and only one method to do the things.

Thanks

**Comment by nlkl** [comment]
Hi!

Although I conceptually tend to agree regarding Bind (Map is not the same as Return and F# etc. also uses the name ‘map’), I’m afraid this would not add enough value to break the API.

/ Nils
