### ISSUE TITLE
Should exists implicit operator between T and Option<T>?

### ISSUE THREAD

**Issue by honzakuzel1989** [nlkl/Optional#75]
Hi,
what is a prefer way to convert `T` to `Option<T>`? I found basic way like
```
Option<T> x = Option.Some<T>(new T());
```
and extension-like way
```
Option<T> x = new T().Some();
```
but something straightforward like 
```
Option<T> x = new T();
```
does not exist yet because probably does not exits implicit operator from T to Option<T>?

What do you mean?

**Comment by vain0x** [comment]
@honzakuzel1989 A related issue exists: #9 

EDIT: and #53

**Comment by honzakuzel1989** [comment]
Ah, ok, i missed that thread. Sorry about that.
