### ISSUE TITLE
Migrate from Optional to the build-in c# Nullable Reference Types

### ISSUE THREAD

**Issue by PawKanarek** [nlkl/Optional#82]
Hi, 
do you have any experience in migration from this `Optional` library to the new c# built-in [Nullable Reference Types](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references)?

**Comment by nlkl** [comment]
Hi!

Do you mean migrating away from Optional to use nullable reference types instead or making Optional play better with nullable references types? (the latter is mostly done in the develop branch, but needs to be refreshed a bit)

If you mean migrating away from Optional I think it should be fairly easy, but will definitely require some manual effort to do so.

**Comment by PawKanarek** [comment]
Thanks @nlkl for reply. 
Im thinking mostly about full transition from `Optional` to NRT.
That new support from C# 8.0 language is very simple and it is built in compiler. In result that native mechanism for null-checking provide better control and is much more resistant for fools-like-me :)
