### ISSUE TITLE
Implicit operator for option type

### ISSUE THREAD

**Issue by janno-p** [nlkl/Optional#9]
Would it be very awful if Option type had implicit operator for converting value from `T => Option<T>`?

```csharp
public static implicit operator Option<T>(T value)
{
     return Option.Some(value);
}
```

It would allow to use shortcut for assigning option values. Instead of `Option<bool> opt = Option.Some(true);` I could use `Option<bool> opt = true;`

**Comment by nlkl** [comment]
Hi Janno,

I will consider this. In general I am not a big fan of implicit conversions, and it does leave some questions to what the conversion behavior should be, e.g. should it return value.Some() or maybe even value.SomeNotNull() etc.

Usually I simply use the extension methods, e.g. `var opt = true.Some();`, which leave very little syntactic overhead.

In my opinion, the only situation in which an implicit conversion "looks nicer", is when converting the return value (e.g. `return true` vs `return true.Some()`). However, this breaks the symmetry between .Some() and .None(), with very little benefit. As such, I do like explicitly choosing the conversion (.Some(), .None(), .SomeNotNull(), .SomeWhen(...), and so on).

Nevertheless, I will give it some thoughts. You are welcome to come up with more pros/cons.

- Nils

**Comment by janno-p** [comment]
Ok. This is all reasonable and those extension methods for conversion really help a lot. Since there are many possible interpretations for this implicit behavior (some might prefer null conversion to None, others might expect Some(null)), then it's hard to make a preference. And when one choice is made it might introduce some unexpected behaviors for end users.

Considering that, I agree, that explicit conversion is much safer way to go and this question is resolved for me.

**Comment by janno-p** [comment]
Waiting for .NET Core compatible NuGet packages to be released :smile:

**Comment by nlkl** [comment]
@janno-p Just FYI, .NET Core support has just been released. Enjoy :)

**Comment by janno-p** [comment]
Great! I will.
